In [1]:
import requests
import pandas as pd
import numpy as np
pd.options.display.max_columns = None

In [2]:
url = 'https://fantasy.premierleague.com/api/bootstrap-static/'
data = requests.get(url)
data = data.json()
data.keys()

dict_keys(['events', 'game_settings', 'phases', 'teams', 'total_players', 'elements', 'element_stats', 'element_types'])

In [3]:
#creating dataframes which we want
elements_df = pd.DataFrame.from_dict(data['elements'])
#element_stats_df = pd.DataFrame.from_dict(data['element_stats'])
element_types_df = pd.DataFrame.from_dict(data['element_types'])

In [4]:
elements_df.columns

Index(['chance_of_playing_next_round', 'chance_of_playing_this_round', 'code',
       'cost_change_event', 'cost_change_event_fall', 'cost_change_start',
       'cost_change_start_fall', 'dreamteam_count', 'element_type', 'ep_next',
       'ep_this', 'event_points', 'first_name', 'form', 'id', 'in_dreamteam',
       'news', 'news_added', 'now_cost', 'photo', 'points_per_game',
       'second_name', 'selected_by_percent', 'special', 'squad_number',
       'status', 'team', 'team_code', 'total_points', 'transfers_in',
       'transfers_in_event', 'transfers_out', 'transfers_out_event',
       'value_form', 'value_season', 'web_name', 'minutes', 'goals_scored',
       'assists', 'clean_sheets', 'goals_conceded', 'own_goals',
       'penalties_saved', 'penalties_missed', 'yellow_cards', 'red_cards',
       'saves', 'bonus', 'bps', 'influence', 'creativity', 'threat',
       'ict_index', 'influence_rank', 'influence_rank_type', 'creativity_rank',
       'creativity_rank_type', 'threat_rank', 'threat_rank_type',
       'ict_index_rank', 'ict_index_rank_type',
       'corners_and_indirect_freekicks_order',
       'corners_and_indirect_freekicks_text', 'direct_freekicks_order',
       'direct_freekicks_text', 'penalties_order', 'penalties_text'],
      dtype='object')

In [5]:
elements_df_reduced = elements_df[['team','id','first_name','second_name','web_name','element_type','minutes','goals_scored','assists','clean_sheets','goals_conceded','penalties_missed','penalties_saved','own_goals','yellow_cards', 'red_cards','now_cost','influence', 'creativity', 'threat','influence_rank', 'influence_rank_type', 'creativity_rank','threat_rank','ict_index','ict_index_rank','status','total_points','points_per_game','bonus','bps','dreamteam_count','selected_by_percent']]

In [6]:
elements_df_reduced.head()

,team,id,first_name,second_name,web_name,element_type,minutes,goals_scored,assists,clean_sheets,goals_conceded,penalties_missed,penalties_saved,own_goals,yellow_cards,red_cards,now_cost,influence,creativity,threat,influence_rank,influence_rank_type,creativity_rank,threat_rank,ict_index,ict_index_rank,status,total_points,points_per_game,bonus,bps,dreamteam_count,selected_by_percent
0,1,1,Mesut,Özil,Özil,3,0,0,0,0,0,0,0,0,0,0,67,0.0,0.0,0.0,713,295,713,713,0.0,713,u,0,0.0,0,0,0,0.5
1,1,2,Sokratis,Papastathopoulos,Sokratis,2,0,0,0,0,0,0,0,0,0,0,48,0.0,0.0,0.0,682,240,674,667,0.0,685,u,0,0.0,0,0,0,0.1
2,1,3,David,Luiz Moreira Marinho,David Luiz,2,1396,1,0,3,20,0,0,0,1,1,54,250.6,46.7,144.0,264,101,346,244,43.9,310,a,41,2.0,0,230,0,0.8
3,1,4,Pierre-Emerick,Aubameyang,Aubameyang,3,2330,10,3,10,26,0,0,1,2,0,113,493.8,361.5,823.0,136,49,101,34,167.4,52,a,131,4.5,11,358,3,7.2
4,1,5,Cédric,Soares,Cédric,2,744,0,1,2,11,0,0,0,1,0,46,110.8,114.8,66.0,366,140,249,330,29.2,356,a,28,2.8,3,125,0,0.3

In [7]:
elements_df_reduced.shape

(713, 33)

In [8]:
#elements_df_reduced['status'].value_counts()

In [9]:
#converting selected_by_percent to float from string
elements_df_reduced = elements_df_reduced.astype({'selected_by_percent':float})

In [10]:
#checking most selected players
elements_df_reduced.sort_values(['ict_index_rank'],ascending=True)

,team,id,first_name,second_name,web_name,element_type,minutes,goals_scored,assists,clean_sheets,goals_conceded,penalties_missed,penalties_saved,own_goals,yellow_cards,red_cards,now_cost,influence,creativity,threat,influence_rank,influence_rank_type,creativity_rank,threat_rank,ict_index,ict_index_rank,status,total_points,points_per_game,bonus,bps,dreamteam_count,selected_by_percent
432,13,302,Bruno Miguel,Borges Fernandes,Fernandes,3,3101,18,14,13,36,1,0,0,6,0,113,1292.6,1414.9,1253.0,2,1,1,11,396.2,1,a,244,6.6,36,870,9,48.7
363,11,254,Mohamed,Salah,Salah,3,3077,22,6,11,41,0,0,0,0,0,129,1056.0,825.7,1980.0,5,2,17,1,385.8,2,a,231,6.2,21,657,4,43.6
572,17,388,Harry,Kane,Kane,4,3083,23,14,12,39,0,0,0,1,0,119,1318.2,659.1,1585.0,1,1,35,3,355.9,3,a,242,6.9,40,880,9,44.5
360,11,251,Sadio,Mané,Mané,3,2808,11,11,12,28,0,0,0,3,0,118,808.8,809.7,1535.0,21,7,19,4,315.5,4,a,176,5.0,14,513,3,8.2
574,17,390,Heung-Min,Son,Son,3,3119,17,11,13,36,0,0,0,0,0,96,1052.2,1049.9,1046.0,6,3,8,16,315.2,5,a,228,6.2,26,777,9,44.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
657,19,444,Jordan,Hugill,Hugill,4,0,0,0,0,0,0,0,0,0,0,55,0.0,0.0,0.0,706,87,707,707,0.0,709,u,0,0.0,0,0,0,0.0
659,19,447,Albian,Ajeti,Ajeti,4,0,0,0,0,0,0,0,0,0,0,55,0.0,0.0,0.0,707,88,708,708,0.0,710,u,0,0.0,0,0,0,0.0
41,2,34,José Ignacio,Peleteiro Romallo,Jota,3,0,0,0,0,0,0,0,0,0,0,59,0.0,0.0,0.0,709,294,710,710,0.0,711,u,0,0.0,0,0,0,0.0
56,2,49,Mbwana,Samatta,Samatta,4,0,0,0,0,0,0,0,0,0,0,59,0.0,0.0,0.0,711,91,712,711,0.0,712,u,0,0.0,0,0,0,0.0
0,1,1,Mesut,Özil,Özil,3,0,0,0,0,0,0,0,0,0,0,67,0.0,0.0,0.0,713,295,713,713,0.0,713,u,0,0.0,0,0,0,0.5

In [11]:
#converting now_cost to now_cost/10

elements_df_reduced['now_cost'] = elements_df_reduced['now_cost']/10

In [12]:
elements_df_reduced

,team,id,first_name,second_name,web_name,element_type,minutes,goals_scored,assists,clean_sheets,goals_conceded,penalties_missed,penalties_saved,own_goals,yellow_cards,red_cards,now_cost,influence,creativity,threat,influence_rank,influence_rank_type,creativity_rank,threat_rank,ict_index,ict_index_rank,status,total_points,points_per_game,bonus,bps,dreamteam_count,selected_by_percent
0,1,1,Mesut,Özil,Özil,3,0,0,0,0,0,0,0,0,0,0,6.7,0.0,0.0,0.0,713,295,713,713,0.0,713,u,0,0.0,0,0,0,0.5
1,1,2,Sokratis,Papastathopoulos,Sokratis,2,0,0,0,0,0,0,0,0,0,0,4.8,0.0,0.0,0.0,682,240,674,667,0.0,685,u,0,0.0,0,0,0,0.1
2,1,3,David,Luiz Moreira Marinho,David Luiz,2,1396,1,0,3,20,0,0,0,1,1,5.4,250.6,46.7,144.0,264,101,346,244,43.9,310,a,41,2.0,0,230,0,0.8
3,1,4,Pierre-Emerick,Aubameyang,Aubameyang,3,2330,10,3,10,26,0,0,1,2,0,11.3,493.8,361.5,823.0,136,49,101,34,167.4,52,a,131,4.5,11,358,3,7.2
4,1,5,Cédric,Soares,Cédric,2,744,0,1,2,11,0,0,0,1,0,4.6,110.8,114.8,66.0,366,140,249,330,29.2,356,a,28,2.8,3,125,0,0.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
708,20,617,Andreas,Söndergaard,Söndergaard,1,0,0,0,0,0,0,0,0,0,0,4.0,0.0,0.0,0.0,556,63,535,512,0.0,565,a,0,0.0,0,0,0,0.2
709,20,626,Patrick,Cutrone,Cutrone,4,23,0,0,0,0,0,0,0,0,0,5.9,0.0,0.0,4.0,710,90,711,436,0.2,511,u,2,1.0,0,5,0,0.0
710,20,629,Nigel,Lonwijk,Lonwijk,2,0,0,0,0,0,0,0,0,0,0,3.9,0.0,0.0,0.0,524,195,500,476,0.0,533,a,0,0.0,0,0,0,0.0
711,20,642,Willian José,Da Silva,Willian José,4,1106,1,1,5,13,0,0,0,0,0,6.8,89.6,165.9,256.0,384,47,212,157,50.9,288,a,40,2.4,3,131,0,0.2
712,20,649,Hugo,Bueno,Bueno,2,0,0,0,0,0,0,0,0,0,0,4.0,0.0,0.0,0.0,567,220,546,523,0.0,576,a,0,0.0,0,0,0,0.0

In [13]:
elements_df_reduced.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 713 entries, 0 to 712
Data columns (total 33 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   team                 713 non-null    int64
 1   id                   713 non-null    int64
 2   first_name           713 non-null    object
 3   second_name          713 non-null    object
 4   web_name             713 non-null    object
 5   element_type         713 non-null    int64
 6   minutes              713 non-null    int64
 7   goals_scored         713 non-null    int64
 8   assists              713 non-null    int64
 9   clean_sheets         713 non-null    int64
 10  goals_conceded       713 non-null    int64
 11  penalties_missed     713 non-null    int64
 12  penalties_saved      713 non-null    int64
 13  own_goals            713 non-null    int64
 14  yellow_cards         713 non-null    int64
 15  red_cards            713 non-null    int64
 16  now_cost             713 non-null    float64
 17  influence            713 non-null    object
 18  creativity           713 non-null    object
 19  threat               713 non-null    object
 20  influence_rank       713 non-null    int64
 21  influence_rank_type  713 non-null    int64
 22  creativity_rank      713 non-null    int64
 23  threat_rank          713 non-null    int64
 24  ict_index            713 non-null    object
 25  ict_index_rank       713 non-null    int64
 26  status               713 non-null    object
 27  total_points         713 non-null    int64
 28  points_per_game      713 non-null    object
 29  bonus                713 non-null    int64
 30  bps                  713 non-null    int64
 31  dreamteam_count      713 non-null    int64
 32  selected_by_percent  713 non-null    float64
dtypes: float64(2), int64(22), object(9)
memory usage: 183.9+ KB

In [14]:
element_types_df

,id,plural_name,plural_name_short,singular_name,singular_name_short,squad_select,squad_min_play,squad_max_play,ui_shirt_specific,sub_positions_locked,element_count
0,1,Goalkeepers,GKP,Goalkeeper,GKP,2,1,1,True,[12],80
1,2,Defenders,DEF,Defender,DEF,5,3,5,False,[],246
2,3,Midfielders,MID,Midfielder,MID,5,2,5,False,[],295
3,4,Forwards,FWD,Forward,FWD,3,1,3,False,[],92

In [15]:
#getting all player stats for each gameweek

for x in elements_df.index:
    print(x)
    element_id = elements_df['id'][x]
    player_url = f'https://fantasy.premierleague.com/api/element-summary/{element_id}/'
    r = requests.get(player_url)
    json = r.json()
    history_df = pd.DataFrame.from_dict(json['history'])
    history_past_df = pd.DataFrame.from_dict(json['history_past'])

    if x == 0 :
        all_history_df = history_df
    else : 
        all_history_df = all_history_df.append(history_df)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712

In [16]:
all_history_df.shape

(24365, 31)

In [17]:
all_history_df.columns

Index(['element', 'fixture', 'opponent_team', 'total_points', 'was_home',
       'kickoff_time', 'team_h_score', 'team_a_score', 'round', 'minutes',
       'goals_scored', 'assists', 'clean_sheets', 'goals_conceded',
       'own_goals', 'penalties_saved', 'penalties_missed', 'yellow_cards',
       'red_cards', 'saves', 'bonus', 'bps', 'influence', 'creativity',
       'threat', 'ict_index', 'value', 'transfers_balance', 'selected',
       'transfers_in', 'transfers_out'],
      dtype='object')

In [18]:
all_history_df_reduced=all_history_df[['element','round','opponent_team','was_home','team_h_score','team_a_score','minutes','total_points','goals_scored','assists','clean_sheets', 'goals_conceded','own_goals', 'penalties_saved', 'penalties_missed', 'yellow_cards','red_cards', 'saves','bonus','bps','influence', 'creativity','threat','ict_index','value','selected']]

In [19]:
all_history_df_reduced

,element,round,opponent_team,was_home,team_h_score,team_a_score,minutes,total_points,goals_scored,assists,clean_sheets,goals_conceded,own_goals,penalties_saved,penalties_missed,yellow_cards,red_cards,saves,bonus,bps,influence,creativity,threat,ict_index,value,selected
0,1,1,8,False,0,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,70,76656
1,1,2,19,True,2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,69,68335
2,1,3,11,False,3,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,69,59793
3,1,4,15,True,2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,68,56403
4,1,5,12,False,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,68,53689
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13,649,34,18,False,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,40,2150
14,649,35,3,True,2,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,40,2242
15,649,36,17,False,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,40,2299
16,649,37,7,False,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,40,2360
17,649,38,13,True,1,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,40,2580

In [20]:
#converting value 
all_history_df_reduced['value'] = all_history_df_reduced['value']/10

<ipython-input-20-6da162c13565>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  all_history_df_reduced['value'] = all_history_df_reduced['value']/10

In [21]:
all_history_df_reduced.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 24365 entries, 0 to 17
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   element           24365 non-null  int64
 1   round             24365 non-null  int64
 2   opponent_team     24365 non-null  int64
 3   was_home          24365 non-null  bool
 4   team_h_score      24365 non-null  int64
 5   team_a_score      24365 non-null  int64
 6   minutes           24365 non-null  int64
 7   total_points      24365 non-null  int64
 8   goals_scored      24365 non-null  int64
 9   assists           24365 non-null  int64
 10  clean_sheets      24365 non-null  int64
 11  goals_conceded    24365 non-null  int64
 12  own_goals         24365 non-null  int64
 13  penalties_saved   24365 non-null  int64
 14  penalties_missed  24365 non-null  int64
 15  yellow_cards      24365 non-null  int64
 16  red_cards         24365 non-null  int64
 17  saves             24365 non-null  int64
 18  bonus             24365 non-null  int64
 19  bps               24365 non-null  int64
 20  influence         24365 non-null  object
 21  creativity        24365 non-null  object
 22  threat            24365 non-null  object
 23  ict_index         24365 non-null  object
 24  value             24365 non-null  float64
 25  selected          24365 non-null  int64
dtypes: bool(1), float64(1), int64(20), object(4)
memory usage: 4.9+ MB

In [22]:
elements_df_reduced.to_excel('FPL_2020-2021_agg_stats.xlsx',index=False)
all_history_df_reduced.to_excel('FPL_2020-2021_weekly_stats.xlsx',index=False)